apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: flintsky
spec:
  template:
    spec:
      containers:
      - name: django
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: flintsky
spec:
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
