apiVersion: v1
kind: Secret
metadata:
  name: flintsky-secrets
  namespace: flintsky
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-dev-key-change-in-production"
  DATABASE_PASSWORD: "postgres"
